name: Preview

on:
  pull_request:
    paths-ignore:
      - ".github/workflows/**"
      - "README.md"
      - "Makefile"
      - ".gitignore"
      - ".devcontainer/**"
      - ".vscode/**"
      - "resources/**"
      - "content/**"

jobs:
  build:
    name: Build
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Build the Preview Website
        uses: rehanhaider/pelican-build-action@v1.0.0
        env:
          PELICAN_CONFIG_FILE: settings.py
          PELICAN_CONTENT_FOLDER: content
          PUBLISH: True
      - name: Upload the build artefacts
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: |
            output/
            .firebaserc
            firebase.json
          retention-days: 1
      - name: Upload the Test Files
        uses: actions/upload-artifact@v2
        with:
          name: test-input
          path: |
            tests/
            requirements.txt
            .github/scripts/prepare-test-env.sh
            pytest.ini
          retention-days: 1
  test:
    name: Test
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Download the Build Output
        uses: actions/download-artifact@v2
        with:
          name: build-output
      - name: Download the test input
        uses: actions/download-artifact@v2

        with:
          name: test-input
      - name: Prepare Test Environment
        run: sh "${{ github.workspace }}/.github/scripts/prepare-test-env.sh"
      - name: Run Tests
        env:
          PUBLISH: True
        run: pytest
  stage:
    name: Stage
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Download the build artefacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
      - name: Deploy to Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLOUDBYTES_PROD }}"
          projectId: cloudbytes-prod
