name: Preview

on:
  pull_request:
    paths-ignore:
      - ".github/workflows/**"
      - "README.md"
      - "Makefile"
      - ".gitignore"
      - ".devcontainer/**"
      - ".vscode/**"
      - "resources/**"

jobs:
  preview:
    name: Preview the PR
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Preview
        uses: rehanhaider/pelican-build-action@v0.1.10
        env:
          PELICAN_CONFIG_FILE: app/pelicanconf.py
          PELICAN_CONTENT_FOLDER: app/content
      - name: Deploy to Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLOUDBYTES_PROD }}"
          projectId: cloudbytes-prod
