name: Preview

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
    branches:
      # Optionally configure to run only for specific files. For example:
      # paths:
      # - "website/**"

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: justgoodin/pelican-build-deploy-anywhere@v0.1.4
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_UBERPYTHON_PROD }}'
        projectId: uberpython-prod