name: Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      #- ".github/workflows/**"
      - "README.md"
      - "Makefile"
      - ".gitignore"
      - ".devcontainer/**"
      - ".vscode/**"
      - "resources/**"

jobs:
  build:
    name: Build the output
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Pelican Website
        uses: rehanhaider/pelican-build-action@v0.1.10
        env:
          PELICAN_CONFIG_FILE: app/publishconf.py
          PELICAN_CONTENT_FOLDER: app/content
          ALGOLIA_ADMIN_API_KEY: "${{ secrets.ALGOLIA_ADMIN_API_KEY }}"
      - name: Upload the build output
        uses: actions/upload-artifact@v2
        with:
          name: pelican-output
          path: |
            output/
            .firebaserc
            firebase.json
          retention-days: 1
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Download the build output
        uses: actions/download-artifact@v2
        with:
          name: pelican-output
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLOUDBYTES_PROD }}"
          channelId: live
          projectId: cloudbytes-prod
