name: Deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: rehanhaider/pelican-build-action@v0.1.10
      env:
        PELICAN_CONFIG_FILE: calepin/publishconf.py
        PELICAN_CONTENT_FOLDER: calepin/content
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_UBERPYTHON_PROD }}'
        channelId: live
        projectId: uberpython-prod